### ISSUE TITLE
Cannot read property crumb of null

### ISSUE THREAD

**Issue by kenkouot** [hapijs/crumb#50]
Hello! For some reason, some of my requests are returning a null object for the value of `requests.state`, resulting in the following error:
```
Stack trace
TypeError: Cannot read property 'crumb' of null
at generate (/usr/www/440/node_modules/crumb/lib/index.js:156:34)
at /usr/www/440/node_modules/crumb/lib/index.js:85:13
at /usr/www/440/node_modules/hapi/lib/handler.js:312:22
at iterate (/usr/www/440/node_modules/hapi/node_modules/items/lib/index.js:35:13)
at Object.exports.serial (/usr/www/440/node_modules/hapi/node_modules/items/lib/index.js:38:9)
at /usr/www/440/node_modules/hapi/lib/handler.js:307:15
at internals.Protect.run (/usr/www/440/node_modules/hapi/lib/protect.js:56:5)
at Object.exports.invoke (/usr/www/440/node_modules/hapi/lib/handler.js:305:22)
at /usr/www/440/node_modules/hapi/lib/request.js:318:32
at iterate (/usr/www/440/node_modules/hapi/node_modules/items/lib/index.js:35:13)
at done (/usr/www/440/node_modules/hapi/node_modules/items/lib/index.js:27:25)
at finish (/usr/www/440/node_modules/hapi/lib/protect.js:45:16)
at wrapped (/usr/www/440/node_modules/hapi/node_modules/hoek/lib/index.js:798:20)
at done (/usr/www/440/node_modules/hapi/node_modules/items/lib/index.js:30:25)
at Function.wrapped [as _next] (/usr/www/440/node_modules/hapi/node_modules/hoek/lib/index.js:798:20)
at Function.internals.continue (/usr/www/440/node_modules/hapi/lib/reply.js:102:10)
```
Any ideas as to what might cause `request.state` to be `null` from hapi? I checked my other plugins and haven't found anything that might unset state generally.

**Comment by stongo** [comment]
What version of hapi are you using? Also can you provide a sample server
code similar to that of your server when this error occurs? Bonus points
for adding a test to reproduce it :)

**Comment by kenkouot** [comment]
Hey @stongo! Thanks for the quick turnaround. The server code is actual open and located [here](https://github.com/Wikia/mercury/blob/dev/server/app.ts#L44). The reproduction steps are actually what I'm stumbling on. I can't reproduce this locally or on our staging server, but on production (where we get tons of traffic) this error occurs <.01% of the time. We are running hapi 8.4.0 and you can find our full list of dependencies [here](https://github.com/Wikia/mercury/blob/dev/package.json).

**Comment by kenkouot** [comment]
Just a quick update, it's actually `request.state` that is a null object.

**Comment by kenkouot** [comment]
Going to close this because it seems the root cause isn't crumb.
